name: Makefile CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/setup

    - name: build
      run: make build
      working-directory: go-metabuild

    - name: Archive build results
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: ./*

  dvd_info:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/setup

    - name: install packages
      run: sudo apt-get install -y libdvdread-dev libmpv-dev

    - name: clone dvd_info
      uses: actions/checkout@v3
      with:
        repository: beandog/dvd_info
        path:       dvd_info

    - name: test dvd_info
      run: make test-dvd_info
      working-directory: go-metabuild


  geeqie:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/setup

    - name: install deps
      run: |
        sudo apt-get install -y gettext libgtk-3-dev libdwarf-dev libarchive-dev \
            libdjvulibre-dev libexiv2-dev libffmpegthumbnailer-dev libdwarf-dev \
            libchamplain-gtk-0.12-dev libclutter-gtk-1.0-dev libheif-dev \
            libopenjp2-7-dev libjpeg-dev liblcms2-dev liblua5.3-dev libdw-dev \
            libpoppler-glib-dev libraw-dev libgspell-1-dev libtiff-dev \
            libunwind-dev yelp-tools

    - uses: actions/checkout@v3
      with:
        repository: BestImageViewer/geeqie.git
        path: geeqie
        ref: master

    - name: build test
      run: make test-geeqie
      working-directory: go-metabuild

  lincity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/setup

    - name: install packages
      run: sudo apt-get install -y gettext

    - name: clone lincity
      uses: actions/checkout@v3
      with:
        repository: oss-qm/lincity
        path:       lincity
        ref:        master

    - name: test lincity
      run: make test-lincity
      working-directory: go-metabuild

  lincity-autoconf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/setup

    - name: install packages
      run: sudo apt-get install -y gettext

    - name: clone lincity
      uses: actions/checkout@v3
      with:
        repository: oss-qm/lincity
        path:       lincity
        ref:        master

    - name: test lincity (autoconf)
      run: make test-lincity-autoconf
      working-directory: go-metabuild

  xfwm4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/setup

    - name: install packages
      run: sudo apt-get install -y gettext libx11-6 libxinerama-dev libxfce4ui-2-dev libxfconf-0-dev libgtk-3-dev libxres-dev libwnck-3-dev

    - name: clone xfwm4
      run: git clone -b sub/testing-6 https://gitlab.xfce.org/metux/xfwm4.git xfwm4

    - name: test xfm4
      run: make test-xfwm4
      working-directory: go-metabuild

  zlib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/setup

    - name: clone zlib
      uses: actions/checkout@v3
      with:
        repository: oss-qm/zlib
        path:       zlib
        ref:        wip/metabuild

    - name: test zlib
      run: make test-zlib
      working-directory: go-metabuild
