name: Makefile CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: update apt db
      run: sudo apt-get update
    - name: install packages
      run: sudo apt-get install -y gettext libx11-6 libxinerama-dev libxfce4ui-2-dev libxfconf-0-dev libgtk-3-dev libxres-dev libwnck-3-dev
    - uses: actions/checkout@v3
      name: clone go-metabuild
      with:
        path: go-metabuild
    - uses: actions/checkout@v3
      name: clone go-magicdict
      with:
        repository: metux/go-magicdict
        path: go-magicdict
        ref: wip/doc
    - uses: actions/checkout@v3
      name: clone zlib
      with:
        repository: oss-qm/zlib
        path: zlib
        ref: wip/metabuild
    - uses: actions/checkout@v3
      name: clone lincity
      with:
        repository: oss-qm/lincity
        path: lincity
        ref: master
    - name: clone xfwm4
      run: git clone -b sub/testing-6 https://gitlab.xfce.org/metux/xfwm4.git xfwm4
    - name: build
      run: make build
      working-directory: go-metabuild
    - name: test zlib
      run: make test-zlib
      working-directory: go-metabuild
    - name: test lincity
      run: make test-lincity
      working-directory: go-metabuild
    - name: test xfwm4
      run: make test-xfwm4
      working-directory: go-metabuild
    - name: Archive build results
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: ./*
